### ISSUE TITLE
Several unexpected worker crashes

### ISSUE THREAD

**Issue by dotta** [triplequote/intellij-scala#40]
Checkout this branch https://github.com/dotta/rchain/commits/issue/following-scala-package-object-convention and import the project in IDEA (make sure to enable Hydra - I used version 1.1.1). Then try to Build the `rspace` module using the IDEA builder, and it should crash with the following error:

```
Warning:scalac: java.lang.AssertionError: assertion failed: 
  object Catscontrib extends Opses {
  def <init>() = {
    super.<init>();
    ()
  }
}
     while compiling: /Users/mirco/tmp/rchain/shared/src/main/scala/coop/rchain/catscontrib/Catscontrib.scala
        during phase: typer
     library version: version 2.12.6
    compiler version: version 2.12.6-hydra29
  reconstructed args: -Xlint:nullary-unit -Xlint:nullary-override -Xlint:infer-any -Xlint:missing-interpolator -Xlint:doc-detached -Xlint:private-shadow -Xlint:type-parameter-shadow -Xlint:poly-implicit-overload -Xlint:option-implicit -Xlint:delayedinit-select -Xlint:by-name-right-associative -Xlint:package-object-classes -Xlint:unsound-match -Xlint:stars-align -Xlint:constant -Ywarn-unused:patvars -Ywarn-unused:privates -Ywarn-unused:locals -Ywarn-unused:implicits -language:dynamics -language:postfixOps -language:reflectiveCalls -language:implicitConversions -language:higherKinds -language:existentials -language:experimental.macros -feature -YpartitionFile /Users/mirco/tmp/rchain/.hydra/idea/shared -Ypartial-unification -classpath /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/charsets.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/deploy.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/cldrdata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/dnsns.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/jaccess.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/jfxrt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/localedata.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/nashorn.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/sunec.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/ext/zipfs.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/javaws.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/jce.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/jfr.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/jfxswt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/jsse.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/management-agent.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/plugin.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/resources.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre/lib/rt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/lib/ant-javafx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/lib/dt.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/lib/javafx-mx.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/lib/jconsole.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/lib/packager.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/lib/sa-jdi.jar:/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/lib/tools.jar:/Users/mirco/tmp/rchain/shared/target/scala-2.12/test-classes:/Users/mirco/tmp/rchain/shared/target/scala-2.12/classes:/Users/mirco/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.2.3.jar:/Users/mirco/.ivy2/cache/org.typelevel/macro-compat_2.12/jars/macro-compat_2.12-1.1.1.jar:/Users/mirco/.ivy2/cache/org.typelevel/machinist_2.12/jars/machinist_2.12-0.6.2.jar:/Users/mirco/.ivy2/cache/org.typelevel/cats-mtl-core_2.12/jars/cats-mtl-core_2.12-0.2.3.jar:/Users/mirco/.ivy2/cache/org.typelevel/cats-macros_2.12/jars/cats-macros_2.12-1.1.0.jar:/Users/mirco/.ivy2/cache/org.typelevel/cats-kernel_2.12/jars/cats-kernel_2.12-1.1.0.jar:/Users/mirco/.ivy2/cache/org.typelevel/cats-effect_2.12/jars/cats-effect_2.12-1.0.0-RC2.jar:/Users/mirco/.ivy2/cache/org.typelevel/cats-core_2.12/jars/cats-core_2.12-1.1.0.jar:/Users/mirco/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.25.jar:/Users/mirco/.ivy2/cache/org.scodec/scodec-core_2.12/bundles/scodec-core_2.12-1.10.3.jar:/Users/mirco/.ivy2/cache/org.scodec/scodec-bits_2.12/bundles/scodec-bits_2.12-1.1.5.jar:/Users/mirco/.ivy2/cache/org.scalatest/scalatest_2.12/bundles/scalatest_2.12-3.0.5.jar:/Users/mirco/.ivy2/cache/org.scalactic/scalactic_2.12/bundles/scalactic_2.12-3.0.5.jar:/Users/mirco/.ivy2/cache/org.scalacheck/scalacheck_2.12/jars/scalacheck_2.12-1.13.4.jar:/Users/mirco/.ivy2/cache/org.scala-sbt/test-interface/jars/test-interface-1.0.jar:/Users/mirco/.ivy2/cache/org.scala-lang.modules/scala-xml_2.12/bundles/scala-xml_2.12-1.0.6.jar:/Users/mirco/.ivy2/cache/org.scala-lang/scala-reflect/jars/scala-reflect-2.12.6.jar:/Users/mirco/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.12.6.jar:/Users/mirco/.ivy2/cache/org.reactivestreams/reactive-streams/jars/reactive-streams-1.0.2.jar:/Users/mirco/.ivy2/cache/org.jctools/jctools-core/bundles/jctools-core-2.1.1.jar:/Users/mirco/.ivy2/cache/io.monix/monix_2.12/jars/monix_2.12-3.0.0-RC1.jar:/Users/mirco/.ivy2/cache/io.monix/monix-tail_2.12/jars/monix-tail_2.12-3.0.0-RC1.jar:/Users/mirco/.ivy2/cache/io.monix/monix-reactive_2.12/jars/monix-reactive_2.12-3.0.0-RC1.jar:/Users/mirco/.ivy2/cache/io.monix/monix-java_2.12/jars/monix-java_2.12-3.0.0-RC1.jar:/Users/mirco/.ivy2/cache/io.monix/monix-execution_2.12/jars/monix-execution_2.12-3.0.0-RC1.jar:/Users/mirco/.ivy2/cache/io.monix/monix-eval_2.12/jars/monix-eval_2.12-3.0.0-RC1.jar:/Users/mirco/.ivy2/cache/com.typesafe.scala-logging/scala-logging_2.12/bundles/scala-logging_2.12-3.7.2.jar:/Users/mirco/.ivy2/cache/com.github.mpilquist/simulacrum_2.12/jars/simulacrum_2.12-0.11.0.jar:/Users/mirco/.ivy2/cache/com.chuusai/shapeless_2.12/bundles/shapeless_2.12-2.3.2.jar:/Users/mirco/.ivy2/cache/ch.qos.logback/logback-core/jars/logback-core-1.2.3.jar -Ywarn-numeric-widen -unchecked -Xfuture -deprecation -YtimingsFile /Users/mirco/tmp/rchain/.hydra/idea/timings.csv -Ymetrics -Xplugin:/Users/mirco/.ivy2/cache/org.scalamacros/paradise_2.12.6/jars/paradise_2.12.6-2.1.0.jar -Xplugin:/Users/mirco/.ivy2/cache/org.spire-math/kind-projector_2.12/jars/kind-projector_2.12-0.9.4.jar -YrootDirectory /Users/mirco/tmp/rchain -cpus 4 -Ywarn-macros:after -Ybackend-parallelism 8 -Ywarn-dead-code -YhydraStore /Users/mirco/tmp/rchain/.hydra/idea/shared/test -sourcepath /Users/mirco/tmp/rchain/shared/src/main/scala:/Users/mirco/tmp/rchain/shared/src/test/scala -YhydraTag shared/test
  last tree to typer: term Catscontrib
       tree position: line 10 of /Users/mirco/tmp/rchain/shared/src/main/scala/coop/rchain/catscontrib/Catscontrib.scala
              symbol: <none>
   symbol definition: <none> (a NoSymbol)
      symbol package: <none>
       symbol owners: 
           call site: <none> in <none>
== Source file context for tree position ==
     7     with ToApplicativeError_Ops
     8     with ToFuturableOps {}
     9 
    10 object Catscontrib extends Opses
    11 
```

Interestingly, if instead of Build you hit Rebuild, a different error is produced:

```
Error:scalac: error while loading IOEvent, class file '/Users/mirco/tmp/rchain/rspace/target/scala-2.12/classes/coop/rchain/rspace/trace/IOEvent.class' has location not matching its contents: contains class IOEvent
```

The above makes me wondering about the logic we have in place to associate sources and classfiles...

Finally, change the builder to use Zinc, and a new crash occurs when you Build

```
Error:scala: A Hydra worker crashed during compilation. This is a bug, please check the .hydra/hydra.log and report the full error.
Warning:scala: java.lang.AssertionError: assertion failed: The startSource can be called only once per source file: /Users/mirco/tmp/rchain/rspace/src/main/scala/coop/rchain/rspace/examples/package.scala
Warning:scala: 
Warning:scala: 	at scala.Predef$.assert(Predef.scala:219)
Warning:scala: 	at sbt.internal.inc.AnalysisCallback.startSource(Compile.scala:167)
Warning:scala: 	at xsbt.API$ApiPhase.processScalaUnit(API.scala:40)
Warning:scala: 	at xsbt.API$ApiPhase.processUnit(API.scala:35)
Warning:scala: 	at xsbt.API$ApiPhase.apply(API.scala:33)
Warning:scala: 	at scala.tools.nsc.Global$GlobalPhase.$anonfun$applyPhase$1(Global.scala:519)
Warning:scala: 	at scala.tools.nsc.Global$GlobalPhase.withCurrentUnitNoLog(Global.scala:504)
Warning:scala: 	at scala.tools.nsc.Global$GlobalPhase.withCurrentUnit(Global.scala:495)
Warning:scala: 	at scala.tools.nsc.Global$GlobalPhase.applyPhase(Global.scala:519)
Warning:scala: 	at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1(Global.scala:475)
Warning:scala: 	at scala.tools.nsc.Global$GlobalPhase.$anonfun$run$1$adapted(Global.scala:475)
Warning:scala: 	at scala.collection.Iterator.foreach(Iterator.scala:944)
Warning:scala: 	at scala.collection.Iterator.foreach$(Iterator.scala:944)
Warning:scala: 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1432)
Warning:scala: 	at scala.tools.nsc.Global$GlobalPhase.run(Global.scala:475)
Warning:scala: 	at xsbt.API$ApiPhase.run(API.scala:27)
Warning:scala: 	at scala.tools.nsc.Global$Run.compileUnitsInternal(Global.scala:1553)
Warning:scala: 	at scala.tools.nsc.Global$Run.compileUnits(Global.scala:1537)
Warning:scala: 	at scala.tools.nsc.Global$Run.compileSources(Global.scala:1530)
Warning:scala: 	at scala.tools.nsc.Global$Run.compile(Global.scala:1681)
Warning:scala: 	at com.triplequote.hydra.compiler.ScalaWorker.compile(ScalaWorker.scala:99)
Warning:scala: 	at com.triplequote.hydra.WorkerThread.$anonfun$run$1(WorkerThread.scala:42)
Warning:scala: 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
Warning:scala: 	at com.triplequote.hydra.compiler.utils.Utils$.timed(Utils.scala:34)
Warning:scala: 	at com.triplequote.hydra.WorkerThread.run(WorkerThread.scala:42)
Warning:scala: java.lang.AssertionError: assertion failed: The startSource can be called only once per source file: /Users/mirco/tmp/rchain/rspace/src/main/scala/coop/rchain/rspace/history/package.scala
```

We need to remove the assertion check since Hydra uses multiple workers and the same package object may be assigned to multiple workers. This is fixed in our sbt-hydra plugin, but the code is not shared with the Hydra IDEA support, hence we need to duplicate the fix.

**Comment by dragos** [comment]
The `startSource` is tracked at triplequote/hydra#467

**Comment by dragos** [comment]
Is this still an issue with the current IJ Hydra plugin? I somehow remember that it was fixed in the 1.0 release.

**Comment by dotta** [comment]
Right. Haven't tested it but the assertion is no longer there so I'm going to close this.

**Comment by dragos** [comment]
Cool! Also please ping the guy on Zendesk, in case he was a customer: https://triplequote.zendesk.com/agent/tickets/33

**Comment by dotta** [comment]
He is not a customer, rather a prospect. Will close the zendesk ticket as well.
